### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by nicdgonzalez** [nicdgonzalez/axiom#1]
# Overview

Use tasks to track what needs to be done on this project.

# Intended outcome

To make progress towards the first production ready release (version 1.0.0).

# Tasks

Verify each command does the following:

- Performs the operation cleanly (e.g., no unnecessary `.unwrap()`s).
- Only outputs useful information to stdout (e.g., outputting the path to the file created by `axiom backup new` so the user can copy it to an external drive, etc.).
- Functions/items are properly documented and tested.

- Server commands:
    - [x] New: Create a new server.
    - [x] Delete: Remove an existing server.
    - [x] Update: Change the version of Minecraft a server is using.
    - [x] List: Display information about the existing servers.
    - [x] Start: Run the server, allowing players to connect to the worlds.
    - [x] Stop: Stop the server, disconnecting all players.
    - [ ] Attach (to console)
    - [ ] Edit: Easily make changes to `server.properties`.
    - [ ] Status: Check if a server is currently running.
    - [ ] ListVersions: Display the available Minecraft versions.
- Backup commands:
    - [x] New: Create a new backup.
    - [ ] Restore: Unpack and use the backup in place of the current server.
    - [ ] List: Display information about the currently recorded backup files.
    - [ ] Delete
- Plugin commands:
    - [ ] New: Add a new plugin to the server.
    - [ ] Delete: Remove an existing plugin from the server.
    - [ ] List: Display information about the current plugins.
    - [ ] Update: Overwrite an existing plugin with new data (for scripts to update plugins programmatically).
    - [ ] Disable: Move a plugin to a temporary folder.
    - [ ] Enable: Move a plugin from the temporary folder back into plugins.

# Future Plans

- [ ] Release v1.0.0
